import nmap
import argparse
import sys
import socket
import csv
import json
import os
import random
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from datetime import datetime

def validate_target(target):
    """validates if the target is a valid IP or hostname."""
    try:
        socket.gethostbyname(target)
        return True
    except socket.error:
        return False

def get_html_template():
    return """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Port Scan Dashboard</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg-color: #121212;
            --card-bg: #1e1e1e;
            --text-color: #e0e0e0;
            --accent-color: #bb86fc;
            --secondary-color: #03dac6;
        }
        body {
            font-family: 'Roboto', sans-serif;
            background-color: var(--bg-color);
            color: var(--text-color);
            margin: 0;
            padding: 20px;
        }
        .container {
            max_width: 1200px;
            margin: 0 auto;
        }
        header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 1px solid #333;
        }
        h1 {
            color: var(--accent-color);
            margin: 0;
        }
        .meta-info {
            font-size: 0.9em;
            color: #888;
        }
        .dashboard-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(500px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        .card {
            background-color: var(--card-bg);
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.3);
        }
        .card h2 {
            margin-top: 0;
            color: var(--secondary-color);
            border-bottom: 1px solid #333;
            padding-bottom: 10px;
        }
        .full-width {
            grid-column: 1 / -1;
        }
        footer {
            text-align: center;
            margin-top: 50px;
            color: #666;
        }
        /* Plotly Override */
        .js-plotly-plot .plotly .main-svg {
            background: transparent !important;
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <div>
                <h1>🛡️ Network Scan Report</h1>
            </div>
            <div class="meta-info">
                <p>Generated: <span id="timestamp"></span></p>
            </div>
        </header>

        <div class="dashboard-grid">
            <div class="card">
                <h2>Protocol Distribution</h2>
                <div id="protocol-chart">{PROTOCOL_CHART}</div>
            </div>
            <div class="card">
                <h2>Top Services</h2>
                <div id="service-chart">{SERVICE_CHART}</div>
            </div>
            <div class="card full-width">
                <h2>Detailed Scan Results</h2>
                <div id="details-table">{DETAILS_TABLE}</div>
            </div>
        </div>

        <footer>
            <p>Generated by Simple Port Scanner CLI</p>
            <p>Created by <strong>Arnab Kumar Das</strong></p>
        </footer>
    </div>
    <script>
        document.getElementById('timestamp').textContent = new Date().toLocaleString();
    </script>
</body>
</html>
"""

def generate_report(scan_data, output_file='scan_report.html'):
    """Generates an enhanced HTML report from scan data."""
    if not scan_data:
        print("No data to visualize.")
        return

    df = pd.DataFrame(scan_data)
    
    if df.empty:
        print("Dataframe is empty.")
        return

    # Themes
    plotly_template = "plotly_dark"

    # 1. Protocols (Pie -> Donut)
    protocol_counts = df['protocol'].value_counts()
    fig1 = px.pie(values=protocol_counts.values, names=protocol_counts.index, template=plotly_template, hole=0.4)
    fig1.update_traces(textposition='outside', textinfo='percent+label')
    fig1.update_layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', annotations=[dict(text='Protocol', x=0.5, y=0.5, font_size=20, showarrow=False)])

    # 2. Services (Bar)
    if 'service' in df.columns:
        service_counts = df['service'].value_counts().head(10) # Top 10
        fig2 = px.bar(x=service_counts.index, y=service_counts.values, labels={'x': 'Service', 'y': 'Count'}, text=service_counts.values, template=plotly_template)
        fig2.update_traces(textposition='auto')
        fig2.update_layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
    else:
        fig2 = go.Figure()

    # 3. Table
    fig3 = go.Figure(data=[go.Table(
        header=dict(values=list(df.columns),
                    fill_color='#333',
                    font=dict(color='white'),
                    align='left'),
        cells=dict(values=[df[col] for col in df.columns],
                   fill_color='#1e1e1e',
                   font=dict(color='#e0e0e0'),
                   align='left'))
    ])
    fig3.update_layout(template=plotly_template, paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', height=600)

    html_template = get_html_template()
    final_html = html_template.replace("{PROTOCOL_CHART}", fig1.to_html(full_html=False, include_plotlyjs='cdn')) \
                              .replace("{SERVICE_CHART}", fig2.to_html(full_html=False, include_plotlyjs=False)) \
                              .replace("{DETAILS_TABLE}", fig3.to_html(full_html=False, include_plotlyjs=False))

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(final_html)
    
    print(f"Visualization report saved to {output_file}")


def save_results_json(results, filepath):
    with open(filepath, 'w') as f:
        json.dump(results, f, indent=4)
        print(f"Results saved to {filepath}")

def save_results_csv(results, filepath):
    if not results:
        return
    keys = results[0].keys()
    with open(filepath, 'w', newline='') as f:
        dict_writer = csv.DictWriter(f, fieldnames=keys)
        dict_writer.writeheader()
        dict_writer.writerows(results)
        print(f"Results saved to {filepath}")

def generate_demo_data():
    services = ['http', 'https', 'ssh', 'ftp', 'smtp', 'dns', 'mysql', 'rdp']
    products = ['nginx', 'Apache', 'OpenSSH', 'vsftpd', 'Postfix', 'dnsmasq', 'MySQL', 'Microsoft RDP']
    data = []
    print("Generating demo data...")
    for _ in range(20):
        idx = random.randint(0, len(services)-1)
        data.append({
            "host": f"192.168.1.{random.randint(1, 254)}",
            "hostname": f"demo-host-{random.randint(1, 100)}",
            "protocol": "tcp",
            "port": random.randint(20, 9000),
            "state": "open",
            "service": services[idx],
            "product": products[idx],
            "version": f"{random.randint(1,9)}.{random.randint(0,9)}"
        })
    return data

def scan_host(target, ports, output_file=None, visualize=False, demo_mode=False):
    scan_data = []

    if demo_mode:
        scan_data = generate_demo_data()
    else:
        scanner = nmap.PortScanner()
        print(f"Starting scan on {target} ports: {ports}...")
        try:
            scanner.scan(hosts=target, ports=ports, arguments='-v -sT -sV --version-light')
        except nmap.PortScannerError as e:
            print(f"Nmap error: {e}")
            sys.exit(1)
        except Exception as e:
            print(f"Unexpected error: {e}")
            sys.exit(1)

        for host in scanner.all_hosts():
            print(f"Host: {host} ({scanner[host].hostname()})")
            for proto in scanner[host].all_protocols():
                ports_list = scanner[host][proto].keys()
                for port in sorted(ports_list):
                    service = scanner[host][proto][port]
                    service_info = {
                        "host": host,
                        "hostname": scanner[host].hostname(),
                        "protocol": proto,
                        "port": port,
                        "state": service.get('state'),
                        "service": service.get('name'),
                        "product": service.get('product', ''),
                        "version": service.get('version', '')
                    }
                    scan_data.append(service_info)

    # Output Handling
    if output_file:
        if output_file.endswith('.json'):
            save_results_json(scan_data, output_file)
        elif output_file.endswith('.csv'):
            save_results_csv(scan_data, output_file)
        else:
            print("Unsupported file format for output. Please use .json or .csv")

    if visualize:
        report_file = "scan_report.html"
        if output_file:
             base_name = os.path.splitext(output_file)[0]
             report_file = f"{base_name}_report.html"
        generate_report(scan_data, report_file)

def main():
    parser = argparse.ArgumentParser(description="Python Nmap Port Scanner")
    parser.add_argument("target", nargs='?', help="Target IP address or hostname to scan")
    parser.add_argument("-p", "--ports", default="1-1024", help="Port range to scan (default: 1-1024)")
    parser.add_argument("-o", "--output", help="Output file path (supports .json, .csv)")
    parser.add_argument("-v", "--visualize", action="store_true", help="Generate HTML visualization report")
    parser.add_argument("--demo", action="store_true", help="Run in demo mode with dummy data (no nmap required)")

    args = parser.parse_args()

    if args.demo:
        scan_host("DEMO", args.ports, args.output, args.visualize, demo_mode=True)
    elif args.target:
        if not validate_target(args.target):
            print(f"Error: Invalid target '{args.target}'. Please provide a valid IP or hostname.")
            sys.exit(1)
        scan_host(args.target, args.ports, args.output, args.visualize, demo_mode=False)
    else:
        parser.print_help()
        sys.exit(1)

if __name__ == "__main__":
    main()
